POST http://localhost:8080/admin/api/users/create
Content-Type: application/json

{
  "nom": "Lahmidi",
    "prenom": "OUSS",
    "email": "o@g.c",
    "role": "RH"
}

###

###
# PUT YOUR API TESTS HERE

GET http://localhost:8080/admin/api/users
Accept: application/json

###

GET http://localhost:8080/salarie/api/profil

###

GET http://localhost:8080/salarie/api/conges

###

GET http://localhost:8080/salarie/api/absences

###

POST http://localhost:8080/salarie/api/conges/create
Content-Type: application/json

{
    "dateFin": "2020-04-04",
    "dateDebut": "2020-05-04",
    "motif": "Conge d'ete",
    "duree": 10,
    "type": {
        "id": 1
    }
}

###

POST http://localhost:8080/salarie/api/absences/create
Content-Type: application/json

{
    "dateFin": "2020-04-04",
    "dateDebut": "2020-05-04",
    "type": "deces"
}

###

GET http://localhost:8080/rh/api/postes/postes

###

GET http://localhost:8080/salarie/api/confirm

###

POST http://localhost:8080/rh/api/postes/create
Content-Type: application/json

{
    "nom": "Gestion RH",
    "division": "DIV V",
    "service": {
        "id": "21"
    },
    "direction": {
        "nom": "dirrr"
    },
    "compentences": ["COM","ETUD"]
}

###
